name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    strategy:
          matrix:
            include:
              - runner: ubuntu-24.04
                arch: amd64
                base: cm2network/steamcmd:root
              - runner: ubuntu-24.04-arm
                base: ghcr.io/sonroyaalmerol/steamcmd-arm64:root
    runs-on: ${{ matrix.runner }}
    permissions:
        contents: read
        packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
              ghcr.io/${{ github.repository }}:${{ matrix.arch }}
          provenance: false
  merge:
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Log in to registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - run: |
            docker manifest create ghcr.io/${{ github.repository }}:latest \
                ghcr.io/${{ github.repository }}:amd64 \
                ghcr.io/${{ github.repository }}:arm64
            docker manifest push ghcr.io/${{ github.repository }}:latest
